---
title: "reading_data_from_the_web"
author: "Hanrui Li"
date: "2024-10-10"
output: github_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)
library(httr)
```

```{r message=FALSE, warning=FALSE}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

Get the pieces I actually need.

```{r}
drug_use_html |>
  html_table()
```

```{r}
marj_use_df =
  drug_use_html |>
  html_table() |>
  first() |>
  slice(-1)

marj_use_df
```


Learning assessment

```{r message=FALSE, warning=FALSE}
nyc_cost_df = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |>
  html_table(header = TRUE) |>
  first()

nyc_cost_df

```


## CSS Selectors

```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()
title_vec

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()
metascore_vec

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()
runtime_vec

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)
swm_df
```


Import some books

```{r}
books_html = read_html("https://books.toscrape.com/")
```

```{r}
books_titles = 
  books_html |>
  html_elements("h3") |>
  html_text2()

books_stars = 
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")

books_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text()

books = 
  tibble(
  title = books_titles,
  stars = books_stars,
  price = books_price)
books
```

## Using an API

Get water data.

```{r message=FALSE}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
nyc_water
```

```{r message=FALSE}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") |> 
  content("text") |>
  jsonlite::fromJSON() |>
  as_tibble()
```

```{r message=FALSE}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")
brfss_smart2010
```

Pokemon API

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()

poke[["name"]]
poke[["height"]]
poke[["abilities"]]

poke$name
poke$height
poke$abilities
```





